code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension formulahendry.code-runner
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension GrapeCity.gc-excelviewer
code --install-extension waderyan.gitblame
code --install-extension njpwerner.autodocstring
code --install-extension thomascsd.vscode-readme-pattern
